-- 初始化数据
-- 注意：这些数据会在应用启动时自动插入（如果表为空）

-- 默认分类数据（这些会在用户注册时复制给新用户）
-- 收入分类
-- INSERT INTO categories (user_id, name, type, icon, color, sort_order, is_active) VALUES
-- (1, '工资', 'INCOME', 'Money', '#52C41A', 1, true),
-- (1, '奖金', 'INCOME', 'Present', '#52C41A', 2, true),
-- (1, '投资收益', 'INCOME', 'TrendCharts', '#52C41A', 3, true),
-- (1, '兼职', 'INCOME', 'Timer', '#52C41A', 4, true),
-- (1, '其他收入', 'INCOME', 'Plus', '#52C41A', 5, true);

-- 支出分类
-- INSERT INTO categories (user_id, name, type, icon, color, sort_order, is_active) VALUES
-- (1, '餐饮', 'EXPENSE', 'Food', '#F5222D', 1, true),
-- (1, '交通', 'EXPENSE', 'Van', '#FA8C16', 2, true),
-- (1, '购物', 'EXPENSE', 'ShoppingBag', '#EB2F96', 3, true),
-- (1, '娱乐', 'EXPENSE', 'VideoPlay', '#722ED1', 4, true),
-- (1, '居住', 'EXPENSE', 'House', '#13C2C2', 5, true),
-- (1, '医疗', 'EXPENSE', 'FirstAidKit', '#CF1322', 6, true),
-- (1, '教育', 'EXPENSE', 'Reading', '#1890FF', 7, true),
-- (1, '其他支出', 'EXPENSE', 'More', '#8C8C8C', 8, true);
